on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - run: nvm install node
      - run: npm install
      - run: npm run delete
      - run: npm run deploy