on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - run: npm install
      - run: npm run delete
      - run: npm run deploy